version: 1
services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
      - key: DATABASE_URL
        value: your_database_url_if_needed
